version: "3.4"
services:
  postgres:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    network_mode: host
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
